# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


variables:
  imageName: 'apama_file_plugin:$(build.buildId)'

jobs:
- job: lin
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: docker build -f Dockerfile -t $(imageName) .
- job: win
  pool:
    vmImage: 'win1803'
  steps:
  - script: docker build -f Dockerfile -t $(imageName) .
